name: Deploy do Site

on:
  push:
    branches:
      - main  # Se a sua branch principal for 'master', troque aqui

jobs:
  web-deploy:
    name: Build e Deploy via FTP
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Instalar dependências
        run: pnpm install --no-frozen-lockfile

      - name: Gerar código do Convex
        run: npx convex codegen || true

      - name: Gerar Build do Vite
        run: pnpm exec vite build

      - name: Enviar arquivos via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
