name: Deploy do Site

on:
  push:
    branches:
      - main  # Se a sua branch principal se chamar 'master', altere aqui para 'master'

jobs:
  web-deploy:
    name: Deploy via FTP
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Enviar arquivos via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # server-dir: /public_html/ # Remova o '#' no início desta linha se precisar enviar para uma pasta específica no servidor
